import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>{`Go Easy`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon_light.svg" />
      </Head>
      <main className="flex min-h-full flex-col items-center justify-center bg-gradient-to-b from-[#0064fe] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image
            src={"/favicon_light.svg"}
            alt={"Go Easy"}
            width={144}
            height={144}
          />
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span>{"Go Easy"}</span>
          </h1>
        </div>
      </main>
    </>
  );
}
